# Site settings
title: CSU Fresno Tree Walk Map
short_title: Tree Walk
email: csaba.toth.us@gmail.com
description: Redesigned tree walk of indigenious, native, and / or drought tolerant specimen around campus.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://treewalks.github.io/ # the base hostname & protocol for your site
copyright: '&copy; 2023 Csaba Toth'

# Website Links
old_tree_walk: https://adminfinance.fresnostate.edu/arboretum/treewalk/index.html
website_source_repo: https://github.com/TreeWalks/TreeWalks.github.io
website_issues: https://github.com/TreeWalks/TreeWalks.github.io/issues/

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: red-indigo

# Android AR Map app
application_name: Tree Walk Guide
app_source_repo: https://github.com/TreeWalks/tree-walk-guide
app_issues: https://github.com/TreeWalks/tree-walk-guide/issues/
play_store_url: https://play.google.com/store/apps/details?id=dev.csaba.arguide.treewalk

# Google Analytics account ID (UA-XXXXXXXX-X)
google-analytics-ua: UA-86563829-10
gmaps_yo: "AIzaSyDUpDuBL2jGSyyYq4f1RtuxtL4X9JsK5jQ"
main_map:
  lat: 36.812263
  lon: -119.746558

# For localization
home_title: Home
contribute_title: Contribute!
old_tree_walk_title: Old Tree Walk
design_title: Design
alternate_names_title: Alternate names
latin_name_title: Latin name
latin_alternates_title: Latin alternate name
extra_url_title: Extra URL
height_title: Height
weight_title: Weight
