# Site settings
title: CSU Fresno Tree Walk Map
short_title: Tree Walk
email: csaba.toth.us@gmail.com
description: Redesigned tree walk of indigenous, native, and / or drought tolerant specimen around campus.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://treewalks.github.io/ # the base hostname & protocol for your site
copyright: '&copy; 2023 Csaba Toth'
locale: en

# Website Links
old_tree_walk: https://adminfinance.fresnostate.edu/arboretum/treewalk/index.html
website_source_repo: https://github.com/TreeWalks/TreeWalks.github.io
en_issues_form: https://docs.google.com/forms/d/e/1FAIpQLSft5aroo2yJYlOmskQbRpjZXTzawHzy1UF3kwcAXptnDduDpg/viewform
es_issues_form: https://docs.google.com/forms/d/e/1FAIpQLSdpQxSCUH8otB-u5j1J1UKhDaOpIkABeRhPCUnTbjcnd6BHMg/viewform
website_issues: https://github.com/TreeWalks/TreeWalks.github.io/issues/

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: red-indigo

# Android AR Map app
application_name: Tree Walk Guide
app_source_repo: https://github.com/TreeWalks/tree-walk-guide
app_issues: https://github.com/TreeWalks/tree-walk-guide/issues/
play_store_url: https://play.google.com/store/apps/details?id=dev.csaba.armap.treewalk

# Google Analytics GA4
google-analytics-ga4: G-L6LLMSMWGT
gmaps_yo: "AIzaSyDUpDuBL2jGSyyYq4f1RtuxtL4X9JsK5jQ"
main_map:
  lat: 36.812263
  lon: -119.746558
